 services:
  php:
    image: php:8.5-apache-trixie
    volumes:
      - .:/var/www/html
    ports:
      - 8087:80
    command: >
      bash -c "
      chown -R www-data:www-data /var/www/html/public/images &&
      chmod -R 775 /var/www/html/public/images &&
      apache2-foreground
      "
    